%YAML:1.0 # need to specify the file type at the top!

lidar:
  enabled: true
  max_n: 1
  do_calib_dt: true
  do_calib_ext: true
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-6
  init_cov_ex_p: 1e-6
  max_range: 6.0
  min_range: 0.5
  chi2_mult: 1
  raw_do_downsample: true
  raw_downsample_size: 0.1
  raw_noise: 0.01
  raw_remove_motion_blur: false # required to set v_angles and h_angles correctly
  raw_point_dt: 1e-6
  map_do_downsample: true
  map_downsample_size: 0.015
  map_noise: 0.001
  map_ngbr_num: 5
  map_ngbr_max_d: 10.0
  map_decay_time: 3600 # sec
  map_decay_dist: 1000 # m
  map_use_icp: false
  map_icp_dist: 30 # m
  plane_max_p2pd: 0.1
  plane_max_condi: 200.0

lidar0:
  timeoffset: 0.048
  T_imu_lidar:
    - [0.961932 ,  0.011329 , -0.273054 , 0.036391]
    - [0.012481 , -0.999919 ,  0.002483  , 0.036193]
    - [-0.273003 , -0.005796 , -0.961996 , -0.066097]
    - [0.000000 , 0.000000,  0.000000,  1.000000]
  topic: "/livox/lidar"

